### ISSUE TITLE
AttributeError: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by dataspun** [hadialqattan/pycln#191]
**Describe the bug** A clear and concise description of what the bug is.

pycln....................................................................Failed
- hook id: pycln
- exit code: 1

Traceback (most recent call last):

  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\Scripts\pycln.EXE\__main__.py", line 7, in <module>
    sys.exit(app())

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\cli.py", line 167, in main
    configs = Config(

  File "<string>", line 18, in __init__

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 34, in __post_init__
    ParseConfigFile(file_path, self)

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 127, in __init__
    self._config.__post_init__()

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 37, in __post_init__
    self._check_regex()

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 110, in _check_regex
    str(self.extend_exclude), regexu.EXCLUDE

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\tomlkit\items.py", line 1415, in __str__
    return str([v.value.value for v in self._iter_items() if v.value is not None])

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\tomlkit\items.py", line 1415, in <listcomp>
    return str([v.value.value for v in self._iter_items() if v.value is not None])

AttributeError: 'str' object has no attribute 'value'

**Environment (please complete the following information):**

- Python Version: python 3.10.9
- Pycln Version: pycln, version 2.1.3
- OS Type: Windows

**Additional context** Add any other context about the problem here.

I mistakenly posted this issue over at [pre-commit](https://github.com/pre-commit/pre-commit/issues/2749) and the kind gentleman there suggested I post here.  Thanks!

**Comment by dataspun** [comment]
Further debug led to the fix in pyproject.toml: there was a typo with `extend_exclude` generating above error versus the correct `extend-exclude` argument.

So not a bug per se, but curiously `foo_bar` does not generate the same error, so why does pycln evaluate `extend_exclude`.  Or is it deep in the internals?  Thoughts @hadialqattan ??

**Comment by hadialqattan** [comment]
Hey @dataspun, I appreciate your enthusiasm and support... I'm a little bit busy these days so I'll have a look asap + I apologize for the late response.

**Comment by hadialqattan** [comment]
@dataspun, could you provide me the pyptoject.toml file that causes the error? (as I couldn't produce it).

**Comment by dataspun** [comment]
@hadialqattan this was the toml section with typo:

```
[tool.pycln]
extend_exclude = [
    'tests/test1.py',
    'tests/test2.py',
]
```

Eventually determined that fixing the argument to `extend-exclude` resolved the error reported above.  But the root cause is elsewhere, because `foo_bar` does not generate the same error: pycln seems to evaluate `extend_exclude` and then crashes.

**Comment by hadialqattan** [comment]
> @hadialqattan this was the toml section with typo:
> 
> ```
> [tool.pycln]
> extend_exclude = [
>     'tests/test1.py',
>     'tests/test2.py',
> ]
> ```
> 
> Eventually determined that fixing the argument to `extend-exclude` resolved the error reported above. But the root cause is elsewhere, because `foo_bar` does not generate the same error: pycln seems to evaluate `extend_exclude` and then crashes.

@dataspun I apologize for the late response but I've just realized that you were providing extend_exclude as a list while it should be a regex expression (for your case you can do `extend_exclude = "(tests/test1.py|tests/test2.py)"`).

BTW, `extend-exclude` does not work, it just gets ignored.

**Comment by hadialqattan** [comment]
For now, I'll close this issue.. if you still think that this is a bug, feel free to open it again. Thanks.
