### ISSUE TITLE
[BUG] using `-a` crashes when having removed multi-line imports

### ISSUE THREAD

**Issue by perfa** [hadialqattan/pycln#79]
**Description:** Running pycln with the `-a` flag crashes with `SyntaxError` when it has cleaned up a multiline import

**To Reproduce:**

1. Take this code snippet:
`pycln_test.py`

```python
# -*- coding: utf-8 -*-
from urllib.parse import quote, unquote, urlparse

from flask import Blueprint, Response, abort, flash, g, jsonify, redirect, render_template, request, session, url_for
from flask_wtf import FlaskForm
from wtforms import (FieldList, Form, FormField, HiddenField, PasswordField, RadioField, SelectField, StringField,
                     SubmitField, TextAreaField, validators)
from wtforms.fields.html5 import EmailField, TelField
from wtforms.validators import DataRequired, Email, InputRequired, Length, Optional, Required


used = [Blueprint, Response, abort, redirect, render_template, request, session, url_for,
        FlaskForm, FieldList, FormField, SelectField, StringField, SubmitField, TextAreaField,
        Required]
   ```

2. Run this Pycln command:

```bash
$ pycln -a pycln_test.py
```
3. Error traceback or unexpected output (if present):

```bash
  pycln_test.py:2:0 'from urllib.parse import quote' has removed! 🔮
  pycln_test.py:2:0 'from urllib.parse import unquote' has removed! 🔮
  pycln_test.py:2:0 'from urllib.parse import urlparse' has removed! 🔮
  pycln_test.py:4:0 'from flask import flash' has removed! 🔮
  pycln_test.py:4:0 'from flask import g' has removed! 🔮
  pycln_test.py:4:0 'from flask import jsonify' has removed! 🔮
  pycln_test.py:6:0 'from wtforms import Form' has removed! 🔮
  pycln_test.py:6:0 'from wtforms import HiddenField' has removed! 🔮
  pycln_test.py:6:0 'from wtforms import PasswordField' has removed! 🔮
  pycln_test.py:6:0 'from wtforms import RadioField' has removed! 🔮
  pycln_test.py:6:0 'from wtforms import validators' has removed! 🔮
  pycln_test.py:8:0 'from wtforms.fields.html5 import EmailField' has removed! 🔮
  pycln_test.py:8:0 'from wtforms.fields.html5 import TelField' has removed! 🔮
  pycln_test.py:9:0 'from wtforms.validators import DataRequired' has removed! 🔮
  pycln_test.py:9:0 'from wtforms.validators import Email' has removed! 🔮
  pycln_test.py:9:0 'from wtforms.validators import InputRequired' has removed! 🔮
  pycln_test.py:9:0 'from wtforms.validators import Length' has removed! 🔮
  pycln_test.py:9:0 'from wtforms.validators import Optional' has removed! 🔮
  pycln_test.py 18 imports has removed! 🚀
Traceback (most recent call last):
  File "/Users/mango/  File "/Users/mango/  File "/Users/mango/  File "/Users/mango/   sys.exit(app())
  File "/Users/mango/my_project/my_projectPassion/venv/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/mango/my_project/my_projectPassion/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mango/my_project/my_proj  File "/Users/mango/my_project/my_proj  File "/Users/mango/my_project/my_proj  Filerv  File "/Users/mango/my_project/my_proj  File "/Users/mango/my_project/my_proj  File ".8  File "/Users/mango/my_project/my_proj  File "/Users/mango/my_project/my_proj el  File "/Users/mango/my_project/my_proj  File "/Users/mango/my_project/my_proj  File "/th  File "/Users/mango/my_project/my_proj  File "/Users/mango/my_project/my_proj  *args, **kwargs)
  File "/Users/mango/my_project/my_projectPassion/venv/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/mango/my_project/my_projectPassion/venv/lib/python3.8/site-packages/pyc  File "/Users/mango/my_project/my_projectPassion/venv/lib/pythrce)
  File "/Users/mango/my_project/my_projectPassion/venv/li  File "/Users/mango/my_project/my_projectPassioor  File "/Users/mango/my_project/my_projectPassion/venv/li  File "/Users/mango/my_project/my_projectPassioor  File "/Users/mrs  File "/Users/mango/my_project/netiga/lib/python3.8/site-packages/pycln/utils/refactor.py", line 165, in _output
    fixed_lines = Refactor.remove_useless_passes(fixed_lines)
  File "/Users/mango/my_project/my_projectPassion/venv/lib/python3.8/site-packages/pycln/utils/refactor.py", line 85, in remove_useless_passes
    tree = ast.parse("".join(source_lines))
  File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 7
    from wtforms.validators import Required
    ^
SyntaxError: invalid syntax
```

4. Unexpected fixed code:

   >
```python
# -*- coding: utf-8 -*-
from urllib.parse import quote, unquote, urlparse

from flask import Blueprint, Response, abort, flash, g, jsonify, redirect, render_template, request, session, url_for
from flask_wtf import FlaskForm
from wtforms import FieldList, FormField, SelectField, StringField, SubmitField, TextAreaField
from wtforms.fields.html5 import EmailField, TelField
from wtforms.validators import DataRequired, Email, InputRequired, Length, Optional, Required


used = [Blueprint, Response, abort, redirect, render_template, request, session, url_for,
        FlaskForm, FieldList, FormField, SelectField, StringField, SubmitField, TextAreaField,
        Required]
```

**Expected behavior**:

1.  Description: The could to run to completion without Exception
2.  Expected output (if present):

```bash
  pycln_test.py:2:0 'from urllib.parse import quote' has removed! 🔮
  pycln_test.py:2:0 'from urllib.parse import unquote' has removed! 🔮
  pycln_test.py:2:0 'from urllib.parse import urlparse' has removed! 🔮
  pycln_test.py:4:0 'from flask import flash' has removed! 🔮
  pycln_test.py:4:0 'from flask import g' has removed! 🔮
  pycln_test.py:4:0 'from flask import jsonify' has removed! 🔮
  pycln_test.py:7:0 'from wtforms.fields.html5 import EmailField' has removed! 🔮
  pycln_test.py:7:0 'from wtforms.fields.html5 import TelField' has removed! 🔮
  pycln_test.py:8:0 'from wtforms.validators import DataRequired' has removed! 🔮
  pycln_test.py:8:0 'from wtforms.validators import Email' has removed! 🔮
  pycln_test.py:8:0 'from wtforms.validators import InputRequired' has removed! 🔮
  pycln_test.py:8:0 'from wtforms.validators import Length' has removed! 🔮
  pycln_test.py:8:0 'from wtforms.validators import Optional' has removed! 🔮
  pycln_test.py 13 imports has removed! 🚀

All done! 💪 😎
13 imports has removed, 1 file has changed.

```

3.  Expected fixed code (if present):

    >

```python
# -*- coding: utf-8 -*-

from flask import Blueprint, Response, abort, redirect, render_template, request, session, url_for
from flask_wtf import FlaskForm
from wtforms import FieldList, FormField, SelectField, StringField, SubmitField, TextAreaField
from wtforms.validators import Required


used = [Blueprint, Response, abort, redirect, render_template, request, session, url_for,
        FlaskForm, FieldList, FormField, SelectField, StringField, SubmitField, TextAreaField,
        Required]
```

**Environment:**

- Python Version: Python 3.8.6
- Pycln Version: pycln, version 1.0.3
- OS Type: MacOs 11.6 (Big Sur)

**Comment by hadialqattan** [comment]
Hi @perfa, this issue has been fixed. The fix will take effect in the next release (soon). Thank you for the feedback. I'm happy to see you around.
