### ISSUE TITLE
[BUG] pycln failing in pre-commit

### ISSUE THREAD

**Issue by NorthIsUp** [hadialqattan/pycln#83]
**Describe the bug** A clear and concise description of what the bug is.
Pycln is failing due to a missing dependency from Typer

**To Reproduce** Steps to reproduce the behavior:

1. Take this code snippet:

```python
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.0.3 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
    - id: pycln
      name: "Clean unused python imports"
      args: [--config=.config/yadm/pyproject.toml]
      files: '.*\.py'
```

2. Run this Pycln command:
   ```bash
   $ pre-commit run --all-files
   ```
3. Error traceback or unexpected output (if present):

```bash
pycln....................................................................Failed
- hook id: pycln
- exit code: 1

Traceback (most recent call last):
  File "/Users/adam/.cache/pre-commit/repoi53mrfw6/py_env-python3/bin/pycln", line 5, in <module>
    from pycln.cli import app
  File "/Users/adam/.cache/pre-commit/repoi53mrfw6/py_env-python3/lib/python3.9/site-packages/pycln/__init__.py", line 7, in <module>
    import typer
  File "/Users/adam/.cache/pre-commit/repoi53mrfw6/py_env-python3/lib/python3.9/site-packages/typer/__init__.py", line 29, in <module>
    from .main import Typer as Typer
  File "/Users/adam/.cache/pre-commit/repoi53mrfw6/py_env-python3/lib/python3.9/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/Users/adam/.cache/pre-commit/repoi53mrfw6/py_env-python3/lib/python3.9/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```

**Environment (please complete the following informations):**

- Python Version: 3.9
- Pycln Version: 1.0.3
- OS Type: macOS

**Additional context** Add any other context about the problem here.

**Comment by hadialqattan** [comment]
Hi, it seems like there's a dependency conflict between `typer` and `click 8` [see](https://github.com/NCAR/jupyter-forward/issues/91). I'll upgrade typer to 0.4.0.

**Comment by hadialqattan** [comment]
@NorthIsUp Thanks a lot for being around with this feedback.
